### ISSUE TITLE
Management tooling - Server status

### ISSUE THREAD

**Issue by lukashornych** [lukashornych/evitalab#103]
Subissue of #117 

evitaDB server now provides server status endpoint (https://github.com/FgForrest/evitaDB/issues/406). This and other tooling could be used to create new type of tab that displayes status of a server of a particular evitaDB connection like so:

![Image](https://github.com/lukashornych/evitalab/assets/13931450/76aa94d3-68ac-4c3e-8f7c-d2ed0f8619cb)

![Image](https://github.com/lukashornych/evitalab/assets/13931450/c7efc5a3-682c-445d-a72d-5b0d0bb66467)

Not sure which metrics/charts we will be able to render, but we can scrape the prometheus endpoint in time to render these charts in time from the point the tab is opened (without history).

The "Open logs" will be just shortcut to #142
The "Open runtime configuration" will open dialog window with printed YAML runtime configuration of evitaDB with actual values. A new API for converting and printing the `io.evitadb.server.configuration.EvitaServerConfiguration` config will be needed.

The tab will be available using context menu on connection or clicking the connection item in the explorer tree. This means that clicking the item in the explorer will not expand the item but will open new tab. Expanding will be possible only through the left-side arrow.

**Comment by lukashornych** [comment]
Moved to #117

**Comment by lukashornych** [comment]
@o-miko I think we should add refresh button for the status and config to the right side of the toolbar so we don't have to reload lab to sync new status

**Comment by o-miko** [comment]
Missing yaml visualization it is only raw text

**Comment by o-miko** [comment]
Missing url for remote connections. It supports only localhost
![image](https://github.com/user-attachments/assets/1752ba5a-b462-45f6-a7cf-4d0e2fa61cbe)

**Comment by lukashornych** [comment]
I will need to reimplement the backend to use the new gRPC server status operation with more data, including all API urls and so on.

**Comment by lukashornych** [comment]
The base status tile is fully implemented. I'll create new issues for the other tiles as they were never truly planned to be implemented in the first phase.
