### ISSUE TITLE
Management tooling - Configuration overview

### ISSUE THREAD

**Issue by novoj** [lukashornych/evitalab#132]
It would be very helpful if we could print current evitaDB instance configuration in evitaLab UI. A simple record `io.evitadb.server.configuration.EvitaServerConfiguration` to formatted JSON would be sufficient. It's kind of clumsy to check which values are overridden and apply them to defaults just in your head. It'd be great if there was a place where we could see the actual configuration for the instance without any hassle.

**Comment by lukashornych** [comment]
I think we discussed it in the past but you didn't want it, perhaps because of security? I'm not sure. But I agree, this could be very useful.

**Comment by novoj** [comment]
I don't think it's a security problem - currently the most sensitive information is the paths on filesystem. And we count with adding an authentication / authorization layer in the future.

**Comment by lukashornych** [comment]
Further discussed in #103
