### ISSUE TITLE
Reloading connection data

### ISSUE THREAD

**Issue by lukashornych** [lukashornych/evitalab#145]
Currently, there is no way to reload the evitaDB connection data (catalogs, collections, schemas, etc) when new catalog or collection is created.

We need to allow manual reloading (button in context menu of connection) as well as internal API for automated reloading.

**Comment by novoj** [comment]
This should be integrated with CDC process.

**Comment by lukashornych** [comment]
Yeah, you are right, we should wait for that with implementation.

**Comment by lukashornych** [comment]
Primitive implementation for reloading displayed data in explorer is done. After I do some refactoring of data caching, I'll try to incorporate this reload into the cached data as well.
