### ISSUE TITLE
Management tooling - Job listing

### ISSUE THREAD

**Issue by lukashornych** [lukashornych/evitalab#146]
Subissue of #117 

For async jobs like generating reports, that take some time to create by evitaDB, we will create separate job listing viewer for each connection, where all these "jobs" will be listed. The listing will be unified for different types of jobs. The evitaLab will provide API for registering such jobs with monitoring etc. Jobs will be usually some reports to generate or backup/restore catalog. The actual logic will be provided by evitaDB.

![Image](https://github.com/lukashornych/evitalab/assets/13931450/507ecb0b-b9cc-423e-b653-a9387c0eadd6)

- [ ] ~~internal model for registering jobs~~ (tasks are created as by-product of specific operation, not creating tasks directly)
- [ ] ~~nternal API for registering jobs~~ (tasks are created as by-product of specific operation, not creating tasks directly)
- [x] UI for registered jobs

**Comment by novoj** [comment]
Some tasks provide progress information in %. Some tasks will provide a file as a result.

**Comment by lukashornych** [comment]
@novoj this will need some backing in evitaDB itself, idk if it's good idea to implement this solely on FE due to the possible page reloads (it can be probably solved by browser storage, but we need to discuss it).

**Comment by novoj** [comment]
What do you have on mind exactly?

**Comment by lukashornych** [comment]
- [ ] implement job type into job listing

**Comment by lukashornych** [comment]
Implemented fully in `dev`.
