### ISSUE TITLE
Cannot specify time for catalog backup

### ISSUE THREAD

**Issue by lukashornych** [lukashornych/evitalab#219]

**Comment by lukashornych** [comment]
https://vuetifyjs.com/en/components/time-pickers/#installation

**Comment by lukashornych** [comment]
Had to create custom `VDateTimeInput` composed of `VDatePicker`, `VTimePicker` and custom `VTimeOffsetPicker` but I think the result is good enough. Working with the offset is bit messy at the boundaries but I think its the best compromise.

https://github.com/user-attachments/assets/9559db6c-0b70-4082-b400-c5f235be2252

cc @novoj

**Comment by novoj** [comment]
It looks great!
