### ISSUE TITLE
UI/UX styling improvements

### ISSUE THREAD

**Issue by lukashornych** [lukashornych/evitalab#48]
Our GD prepared some graphics changes (colors, icons, styling) that would match our [evitaDB docs. portal](https://evitadb.io/documentation/index?lang=evitaql) and would look nicer. 
We need to incorporate those changes into our codebase.

Ideally, we want most of the changes to done globally by defining custom theme in `src/plugins/vuetify.ts` ([docs](https://vuetifyjs.com/en/styles/colors/#material-colors)) and overriding default props for Vuetify components.
Other options are to override global CSS in `src/styles/settings.scss` or change styling directly in the custom components, but this should be used sparingly. 

Currently used icons: https://pictogrammers.com/library/mdi/

To-Do
- [x] create new Vuetify theme based on the prepared design
- [x] modify icons based on the prepared design (consider changing icon font?)
- [x] change CodeMirror theme to match the evitaDB docs if possible (some themes are at https://thememirror.net/)
- [x] some custom components needs to be modified based on the prepared design
- [x] change evitaLab icon to new one in `README.md`, `.idea`, favicon, and so on
- [x] create new print screen from demo on our `README.md` with new design (@lukashornych)

**Comment by MiroslavAlt** [comment]
@lho - I have prepared styles/features acordingly. Have a look.

**Comment by lukashornych** [comment]
@MiroslavAlt It's awesome :heart_eyes: it's very pleasant to use. Good job :+1: 
Just a few small things I found, nothing major + some things we talked about already:

### Most likely bugs
- [ ] i see updated logo only on welcome page, not in favicon, top left button and so on
- [ ] text inputs has weird light corners
- [ ] trailing text input buttons has incorrect background color
![image](https://github.com/lukashornych/evitalab/assets/13931450/3ed67bc8-c564-4583-8539-dcfd721fb010)
![image](https://github.com/lukashornych/evitalab/assets/13931450/1be79503-6cac-4062-b2d5-dd924feba458)
- [ ] in grid the filter and order inputs has corners with incorrect background color and entire inputs display dotted border on click
![image](https://github.com/lukashornych/evitalab/assets/13931450/8a677017-002d-44b8-aa15-078a66aa05cc)
- [ ] wouldn't it be better if the nav items (currently only `Connections explorer`) don't have the blue circle when not selected? I would imagine that if we have more nav items and all have circles, it would be confusing for  users to distinguish which one is selected
- [ ] in system GraphQL, schema viewer of catalog schema and error viewer, the breadcrums in toolbar doesn't match coloring of other toolbars, i would image that if there is only one item, it would be blue
![image](https://github.com/lukashornych/evitalab/assets/13931450/eaf1029d-2cec-4713-8efb-50f4dc41d92e)
- [ ] toolbar buttons in grid doesn't have same on hover effect, the left one has gradient and the other ones has default circle, personally i would not use the gradient, I think its to much on the blue background, but I know it's based on the GD
  - also all buttons used in toolbar in other tabs use the old circular on hover effect as well

### Nice to have
- [ ] analyze if it's possible to have resizable `Connections Explorer`
- [ ] i would open the blog post in new tab
- [ ] could we make text select background color in codemirror more visible?
- [ ] could we make the AWESOME bubble animation so that the bubbles lose opacity overtime so it flickers less?
- [ ] looking at the GD, there is nice blue circular glow from the bottom, would it be too difficult to implement it? Or at least have it on the welcome page?

**Comment by lukashornych** [comment]
@MiroslavAlt FYI: When trying to solve issues with the green almost non-visible codemirror code selection and autocomplete popup, I've discovered that we tried to use two different codemirror themes simultanously :smile: They were somehow rewriting each other and the used token coloring wasn't even from the used dracula theme. After fixing this, I've discovered that the thememirror's dracula theme is not quite working, there for still problem with the token selection. So I've found different version https://github.com/dennis84/codemirror-themes which seems to work quite good, the selection is cleary visible and the autocomplete too. 

Also, I've notice that on the evitaDB web although the theme for prism is called in dracula in our code, really it's the default vsDark which is not similar to dracula nor the Visual Studio One Dark. I wanted to use this theme in lab as well, but it seems that it's Prism-specific. We should discuss it more.

**Comment by lukashornych** [comment]
@MiroslavAlt I've made couple fixed/changes, please look at the changes so you know what's been done.
Also, I've corrected the variants on VChips as we've talked about, i.e. `plain` for non-clickable and `outline` for actionable.

**Comment by lukashornych** [comment]
@MiroslavAlt I've implemented the RSS feed fetcher. Only problem is CORS headers on the RSS feed endpoint, so I've prepared MR for the evitaDB web, please look at it when you have time.

**Comment by lukashornych** [comment]
@MiroslavAlt FYI I've merged the reworked grid cell detail window from #8 to this branch, so that we could review its UI/UX. Some fixes needed to be done, but now it seems quite ok to me,

**Comment by lukashornych** [comment]
@MiroslavAlt I've changed toast notification coloring according to alert/notes on evitaDB web. Is it okay with you? I had to improvise little bit, because on the evitaDB web the background color is transparent so it blends with the background which I didn't want because there may be values underneath, but overall we use same background as on the evitaDB web so it should match.

![success](https://github.com/lukashornych/evitalab/assets/13931450/a20cb88e-0d13-4dbf-ab54-6ef467a1c070)
![info](https://github.com/lukashornych/evitalab/assets/13931450/28a5c1ce-711b-4d16-b326-9cf98e451c63)
![error](https://github.com/lukashornych/evitalab/assets/13931450/354d60ae-e225-401c-b927-888f48c36b80)

**Comment by MiroslavAlt** [comment]
> @MiroslavAlt I've implemented the RSS feed fetcher. Only problem is CORS headers on the RSS feed endpoint, so I've prepared MR for the evitaDB web, please look at it when you have time.

Merged!

**Comment by MiroslavAlt** [comment]
> @MiroslavAlt I've changed toast notification coloring according to alert/notes on evitaDB web. Is it okay with you? I had to improvise little bit, because on the evitaDB web the background color is transparent so it blends with the background which I didn't want because there may be values underneath, but overall we use same background as on the evitaDB web so it should match.
> 
> ![success](https://user-images.githubusercontent.com/13931450/275341485-a20cb88e-0d13-4dbf-ab54-6ef467a1c070.png) ![info](https://user-images.githubusercontent.com/13931450/275341484-28a5c1ce-711b-4d16-b326-9cf98e451c63.png) ![error](https://user-images.githubusercontent.com/13931450/275341476-354d60ae-e225-401c-b927-888f48c36b80.png)
> 
> EDIT: since than, I've managed to fix the icons to outline versions to match.

Brilliant, thank you!

**Comment by lukashornych** [comment]
- [ ] this over effect and active blue color is not working in firefox
![image](https://github.com/lukashornych/evitalab/assets/13931450/43486620-36fb-45d9-aeaf-5ef4cf4eded2)
- [ ] will we keep this rectangular change for standard buttons ?
![image](https://github.com/lukashornych/evitalab/assets/13931450/173cd812-e283-48d4-97b6-8a8786d612d9)
- [ ] padding in this dialog window seems to be unique only for this window
![image](https://github.com/lukashornych/evitalab/assets/13931450/562f1fb7-41ff-4aa7-bbd2-f851ad3e9a11)
- [ ] plain chips should be clickable/hoverable
![image](https://github.com/lukashornych/evitalab/assets/13931450/ada3676c-ad73-42a9-911d-2316783920eb)
- [ ] shouldn't this background color be used only for codeblocks and base background color for other markdown text be blue like in docs? Also the codeblock may be placed inside longer text (some website post?) so it should be in its own box
![image](https://github.com/lukashornych/evitalab/assets/13931450/db240b68-7e3d-418e-8a85-ca99f09a188b)
![image](https://github.com/lukashornych/evitalab/assets/13931450/afbbe48d-d502-4e99-908e-fc46be474c9e)
- we still have weird corners on dialog
![image](https://github.com/lukashornych/evitalab/assets/13931450/3a7f7d4a-e370-4137-8733-89a15ce26914)

**Comment by lukashornych** [comment]
- [ ] To me: try to render HTML in cell detail.

**Comment by lukashornych** [comment]
FYI: After some thinking, I want to release this as `1.0.0` so there cannot be any `alpha` working on welcome screen, and `(breaking)` commit must exist.

**Comment by MiroslavAlt** [comment]
> FYI: After some thinking, I want to release this as `1.0.0` so there cannot be any `alpha` working on welcome screen, and `(breaking)` commit must exist. Also, I need to aggregate all important changes and new feature for the release summary.
> 
> Maybe we could wait for #52 and representative attributes?

@lho I've made changes as discussed here and on out meetings.
