### ISSUE TITLE
Entity grid listing displays UNKNOWN price inner handling even if it's set

### ISSUE THREAD

**Issue by novoj** [lukashornych/evitalab#49]
See query:

```graphql
query {
  getProduct(primaryKey: 63049) {
    priceInnerRecordHandling
  }
}
```

With result:

![image](https://github.com/lukashornych/evitalab/assets/202912/c33b40d7-296b-4dc8-9494-868d19bd3808)

Yet the grid displays:

![image](https://github.com/lukashornych/evitalab/assets/202912/0c86831d-d7c4-44eb-9940-69633cb47321)

**Comment by lukashornych** [comment]
Yeah, I know about it, just didn't have time to shove it yet. However, what i found so far, the lab API returns wrong data. 

Anyway, i will need to look into it, thanks for the report.

**Comment by lukashornych** [comment]
As a side note, if GraphQL is used instead, the price inner handling is displayed correctly.

**Comment by lukashornych** [comment]
Fixed, incorrect `priceContent()` was used in the query builder for evitaQL.
