### ISSUE TITLE
Missing reference attributes

### ISSUE THREAD

**Issue by novoj** [lukashornych/evitalab#52]
This issue is just a reminder from our discussion on Discord. Currently it's not possible to select reference attributes as columns of a grid view.

**Comment by lukashornych** [comment]
We need to implement detail rendering for such attributes. Currently, the actual attributes can be viewed only in JSON renderer, but in the final version, each reference should have its own panel with list of attributes.

**Comment by lukashornych** [comment]
Basic reference attribute support is finished without the above mentioned items.
