### ISSUE TITLE
Usability improvements

### ISSUE THREAD

**Issue by novoj** [lukashornych/evitalab#8]
This issue was created to track ideas for lab usability improvements:

- [x] for localized columns, instead of `<null>`, display `<no locale selected>` (and mark localized attributes in the column heading with some character - for example the same as selection widget: ![image](https://github.com/lukashornych/evitalab/assets/202912/4ee77177-5e6e-4089-b97f-a600feec732e))
- [x] distinguish column headers that are sortable from those that cannot be clicked on and sorted by (![image](https://github.com/lukashornych/evitalab/assets/202912/3b2aef7d-bca2-46f8-8328-60612cd5a399)
 sign?!)
- [x] allow selection of entire groups of column by their type (attribute, associated data, relation etc.)
- [x] add page size 25 for bigger monitors
- [x] add JSON / HTML renderer for preview of the column value
- [x] allow following relations by clicking on the referenced primary key of the entity
  - [ ] allow reversed relations following by Ctrl+Click on the referenced primary key, this will either find all entities in currently viewed collection that has reference to that clicked entity, or ideally it would show small menu with all collection that has the clicked reference and find all entities in that target collection

**Comment by lukashornych** [comment]
I tried to implement displaying flag emoji for selected locale in the data grid toolbar, but unfortunately (as I suspected) this is not possible, because locales are not country codes (even though, they may contain them, but not always). For example, `en` doesn't reliably correspond to any single country flag (it may be GB, US, and so on). 

I've, at least, now display different icon for when no locale is selected and when any locale is selected.

**Comment by novoj** [comment]
I found out that it's not possible to access attributes defined on references in a grid view. Would it be possible to add them there?

**Comment by lukashornych** [comment]
I know, so far didn't come up with good way to implement it in the UI. Do you have any idea how would they be displayed in the grid?

**Comment by novoj** [comment]
This is the way how we display it in the example results:

| entityPrimaryKey | 🔗 relatedProducts: category                                                                      |
| ---------------- | ------------------------------------------------------------------------------------------------- |
| 103988           | 🔗 104481: 'alternativeProduct', 🔗 104500: 'alternativeProduct'                                  |
| 104008           | 🔗 104708: 'alternativeProduct', 🔗 104718: 'alternativeProduct'                                  |
| 104084           | 🔗 104526: 'alternativeProduct', 🔗 104737: 'alternativeProduct'                                  |
| 104171           | 🔗 104599: 'alternativeProduct', 🔗 104944: 'alternativeProduct'                                  |
| 104227           | 🔗 104481: 'alternativeProduct', 🔗 104526: 'alternativeProduct', 🔗 105093: 'alternativeProduct' |
| 104305           | 🔗 104737: 'alternativeProduct', 🔗 105040: 'alternativeProduct'                                  |
| 104368           | 🔗 104461: 'alternativeProduct', 🔗 104896: 'alternativeProduct'                                  |
| 104392           | 🔗 104500: 'alternativeProduct', 🔗 104718: 'alternativeProduct'                                  |
| 104447           | 🔗 103988: 'alternativeProduct', 🔗 104676: 'alternativeProduct', 🔗 105093: 'alternativeProduct' |
| 104452           | 🔗 104526: 'alternativeProduct', 🔗 104876: 'alternativeProduct'                                  |
| 104461           | 🔗 104305: 'alternativeProduct', 🔗 104761: 'alternativeProduct'                                  |
| 104467           | 🔗 104435: 'alternativeProduct', 🔗 104744: 'alternativeProduct', 🔗 104776: 'alternativeProduct' |
| 104481           | 🔗 104816: 'alternativeProduct', 🔗 105093: 'alternativeProduct'                                  |
| 104490           | 🔗 104567: 'alternativeProduct', 🔗 105022: 'alternativeProduct'                                  |
| 104718           | 🔗 104392: 'alternativeProduct', 🔗 104567: 'alternativeProduct', 🔗 104927: 'alternativeProduct' |
| 104725           | 🔗 104708: 'alternativeProduct', 🔗 104744: 'alternativeProduct', 🔗 105093: 'alternativeProduct' |
| 104732           | 🔗 104508: 'alternativeProduct', 🔗 104705: 'alternativeProduct', 🔗 104851: 'alternativeProduct' |
| 104737           | 🔗 103988: 'alternativeProduct', 🔗 104927: 'alternativeProduct', 🔗 105093: 'alternativeProduct' |
| 104744           | 🔗 104008: 'alternativeProduct'                                                                   |
| 104761           | 🔗 104526: 'alternativeProduct', 🔗 104843: 'alternativeProduct'                                  |

###### **Page** 1/146 **(Total number of results: 2918)**

**Comment by lukashornych** [comment]
Oh okay, I can't seem to find it anywhere in examples. Anyway, that could work, however, such wide column would be clipped to defined max width, which would result in showing only the first attributes on the first glance, so Idk if from this POV it would be ideal. There are of course other things to think about (property selector, property detail...) but those are more of implementation details.

**Comment by lukashornych** [comment]
The branch `feature-8-better-grid-cell-detail-renderer` was merged into https://github.com/lukashornych/evitalab/issues/48 where we finish it with UI/UX styling.

**Comment by lukashornych** [comment]
Closing as all tasks were implemented, the reference attributes are being solved in #52
